### ISSUE TITLE
Unknown file extension when running `yarn generate`

### ISSUE THREAD

**Issue by leohhhn** [gnolang/gno-by-example#154]
## Description

Posting this here since someone else might also run into this error while running `yarn generate`:
```
❯  yarn generate
yarn run v1.22.21
warning ../../../package.json: No license field
$ npx ts-node ./scripts/generate.ts
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /Users/sasurai/Desktop/gno/gbe/scripts/generate.ts
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:160:9)
    at defaultGetFormat (node:internal/modules/esm/get_format:203:36)
    at defaultLoad (node:internal/modules/esm/load:143:22)
    at async nextLoad (node:internal/modules/esm/hooks:750:22)
    at async nextLoad (node:internal/modules/esm/hooks:750:22)
    at async Hooks.load (node:internal/modules/esm/hooks:383:20)
    at async handleMessage (node:internal/modules/esm/worker:199:18) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
```

`Node: v21.5.0`
`ts-node: v10.9.2`
`tsc: v5.4.5`

Currently investigating.

**Comment by leohhhn** [comment]
Seems node & ts-node versions might be incompatible for some reason. After switching to `node v19.0.0`, this issue seems fixed, but we are presented with another one:

```
> yarn generate
yarn run v1.22.21
warning ../../../package.json: No license field
$ npx ts-node ./scripts/generate.ts
/Users/sasurai/Desktop/gno/gbe/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
scripts/generate.ts:149:32 - error TS2345: Argument of type 'Promise<string>' is not assignable to parameter of type 'string | ArrayBufferView'.
  Type 'Promise<string>' is missing the following properties from type 'DataView': buffer, byteLength, byteOffset, getFloat32, and 19 more.

149   fs.writeFileSync(tsFilePath, prettier.format(output, { parser: 'babel' }));
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  scripts/generate.ts:149:32
    149   fs.writeFileSync(tsFilePath, prettier.format(output, { parser: 'babel' }));
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Did you forget to use 'await'?
scripts/generate.ts:220:34 - error TS2345: Argument of type 'Promise<string>' is not assignable to parameter of type 'string | ArrayBufferView'.

220     fs.writeFileSync(outputFile, formattedOutput);
                                     ~~~~~~~~~~~~~~~

  scripts/generate.ts:220:34
    220     fs.writeFileSync(outputFile, formattedOutput);
                                         ~~~~~~~~~~~~~~~
    Did you forget to use 'await'?

    at createTSError (/Users/sasurai/Desktop/gno/gbe/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/Users/sasurai/Desktop/gno/gbe/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/Users/sasurai/Desktop/gno/gbe/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/Users/sasurai/Desktop/gno/gbe/node_modules/ts-node/src/index.ts:1433:41)
    at transformSource (/Users/sasurai/Desktop/gno/gbe/node_modules/ts-node/src/esm.ts:400:37)
    at /Users/sasurai/Desktop/gno/gbe/node_modules/ts-node/src/esm.ts:278:53
    at async addShortCircuitFlag (/Users/sasurai/Desktop/gno/gbe/node_modules/ts-node/src/esm.ts:409:15)
    at async nextLoad (node:internal/modules/esm/loader:161:22)
    at async ESMLoader.load (node:internal/modules/esm/loader:593:20)
    at async ESMLoader.moduleProvider (node:internal/modules/esm/loader:445:11) {
  diagnosticCodes: [ 2345, 2345 ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by zivkovicmilos** [comment]
Fixed with:
https://github.com/gnolang/gno-by-example/commit/adb88ca0016274688dfce14814fce8d1dccb1646
