### ISSUE TITLE
Multiple sections break tutorial generation script

### ISSUE THREAD

**Issue by leohhhn** [gnolang/gno-by-example#160]
## Description

The README does not document the exact way to add new sections, so I tried with the logical approach:
<img width="238" alt="Screenshot 2024-04-17 at 16 03 14" src="https://github.com/gnolang/gno-by-example/assets/33522493/471d889a-ab79-41da-a72c-c2bcb5160232">

Investigating and printing out errors, this is what it comes up with:
```bash
❯ yarn generate
yarn run v1.22.21
warning ../../../package.json: No license field
$ npx tsx ./scripts/generate.ts
Subdirs found:  [ 'basics', 'chain' ]
There should be only one .md file in the directory
✅ Generated tutorial for: src/tutorials/gno.land/gbe/basics
There should be only one .md file in the directory
✅ Generated tutorial for: src/tutorials/gno.land/gbe/chain
❌ Error encountered during tutorial generation TypeError: Cannot read properties of undefined (reading 'link')
    at <anonymous> (/Users/sasurai/Desktop/gno/gbe/scripts/generate.ts:165:52)
    at Array.forEach (<anonymous>)
    at generateTutorialRoutes (/Users/sasurai/Desktop/gno/gbe/scripts/generate.ts:164:9)
    at generateTutorials (/Users/sasurai/Desktop/gno/gbe/scripts/generate.ts:253:9)
✨  Done in 1.78s.
```

EDIT: from the README, I think the idea was to keep all tutorials in on the same level in the tutorials/gno.land/gbe/ dir. It will prove a bit difficult to organize tutorials without support for actual subfolders, instead of just writing the name of the section in the README of the tutorial.

I added section folder support in #162.

**Comment by leohhhn** [comment]
Fixed in #162
